### ISSUE TITLE
Undo formatting?

### ISSUE THREAD

**Issue by kumuwai** [arcs-/MediumButton#2]
Very nice tool! Thank you!

There are a couple of minor issues that I have seen. First, the use-indicator seems to always be on for custom buttons. Second, clicking the button a second time to unformat the text does not work, unless you select all of the formatted text, and some unformatted text next to it, and then click the button.

My buttons look like this:

``` js
'red':  new MediumButton({label:'<span style="color:red">R</span>', start:'<span style="color:red">', end:'</span>'}),
'yellow-highlight':  new MediumButton({label:'<span style="background-color:yellow">Y</span>', start:'<span style="background-color:yellow">', end:'</span>'}),
```

**Comment by arcs-** [comment]
Hello
I'm already working on a new version, which should fix most of the problems. 
However, I can't reproduce your error. Can you tell me the browser and OS you're using?

**Comment by fouineux** [comment]
Hello.

Found this issue too on Chrome.

For example, select the word 'test' in the sentence 'this is a test', turn it to red with the 'red' MediumButton, all works fine. Then if you want to unformat the word 'test', you should select it and click again on your 'red' button : that doesn't works. You have to select unformatted text near the formated word, which allow MediumButton to detect that this word is actually formatted.

I think it's this issue which cause the use-indicator to be always on since we use our button once. I fixed it by adding a else statement in the checkState function (maybe dirty, but seems to work :) ):

``` javascript
MediumButton.prototype.checkState = function(node) {
    var html = getCurrentSelection();
    if (this.options.start != '' && html.indexOf(this.options.start) > -1 && html.indexOf(this.options.end) > -1) {
        this.button.classList.add('medium-editor-button-active');
    } else {
        this.button.classList.remove('medium-editor-button-active');
    }

};
```

**Comment by mrdoinel** [comment]
I have got the same issue.
(on latest Chrome)

**Comment by coreybutler** [comment]
Same issue on Chrome 43, OSX 10.10.4. The fix above worked... perhaps @fouineux could submit a pull request with the change until the new version is ready.

**Comment by r3verser** [comment]
Looks like the problem still exists! @fouineux where should i put your code snippet, to get problem fixed? Thanks.

**Comment by arcs-** [comment]
should now be fixed
